# Generated by Django 2.2.4 on 2020-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
