# Generated by Django 2.2.4 on 2020-05-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_auto_20200521_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='user_id',
            new_name='user',
        ),
    ]
