# Generated by Django 2.2.4 on 2020-05-27 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('shows_app', '0003_auto_20200521_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='medium',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='total_episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='total_seasons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='login_app.User'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='login_app.User')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shows_app.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='login_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.ManyToManyField(related_name='shows', to='shows_app.Genre'),
        ),
    ]
