# Generated by Django 2.2.4 on 2020-05-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('shows_app', '0004_auto_20200526_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='show',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='show',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='show',
            name='total_episodes',
        ),
        migrations.RemoveField(
            model_name='show',
            name='total_seasons',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shows_app.Show'),
        ),
    ]
