# Generated by Django 2.2.4 on 2020-05-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('shows_app', '0006_auto_20200526_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ManyToManyField(related_name='wishlist', to='shows_app.Show')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='login_app.User')),
            ],
        ),
    ]
