# Generated by Django 2.2.4 on 2020-05-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0007_wlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlist',
            name='show',
            field=models.ManyToManyField(related_name='watchlist', to='shows_app.Show'),
        ),
        migrations.AlterField(
            model_name='wlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='login_app.User'),
        ),
    ]
