# Generated by Django 2.2.4 on 2020-05-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0008_auto_20200527_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='imagedb',
            field=models.FileField(null=True, upload_to='img/posters/', verbose_name=''),
        ),
    ]
