# Generated by Django 2.2.4 on 2020-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0009_show_imagedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='imagedb',
        ),
        migrations.AddField(
            model_name='show',
            name='photo',
            field=models.FileField(blank=True, upload_to='img/posters/'),
        ),
    ]
