# Generated by Django 2.2.4 on 2020-05-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0010_auto_20200528_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='photo',
            field=models.FileField(blank=True, upload_to='posters/'),
        ),
    ]
